#!/usr/bin/python

import os, json

tfname = "template.html"
embed_mark = "<!--markdown-->"

# get template
def extract_template(path):
    f = open(path)
    s = f.read()
    f.close()
    a = s.find(embed_mark)
    b = a + len(embed_mark)
    return s[:a], s[b:]

def process_file(input_name, output_name, head, tail):
    f = open(output_name, "w")
    f.write(head)
    f.close()
    os.system("md2html '{}' >> '{}'".format(input_name, output_name))
    f = open(output_name, "a")
    f.write(tail)
    f.close()

def walk(path):
    for dpath, dnames, fnames in os.walk(path):
        if tfname in fnames:
            ls = []
            tfpath = "{}/{}".format(dpath, tfname)
            (head, tail) = extract_template(tfpath)
            for fn in fnames:
                if fn.endswith(".md"):
                    name = fn[:-3]
                    process_file(
                        "{}/{}.md".format(dpath, name),
                        "{}/{}.html".format(dpath, name),
                        head, tail)
                    ls.append(name)
            if len(ls) > 0:
                # sort ls by ctime of md files
                def ncmp(n1, n2):
                    f1 = "{}/{}.md".format(dpath, n1)
                    f2 = "{}/{}.md".format(dpath, n2)
                    t1 = os.path.getmtime(f1)
                    t2 = os.path.getmtime(f2)
                    return cmp(t1, t2)
                ls.sort(ncmp, reverse=True)
                # name ls ==> html path ls
                ls = map(lambda name: "{}/{}.html".format(dpath, name),
                         ls)
                dump_list(dpath, ls)
            for dir in dnames:
                walk("{}/{}".format(dpath, dir))

def dump_list(path, ls):
    # dump articles
    lfile = open("{}/list.json".format(path), "w")
    lfile.write(json.dumps(ls))
    lfile.write("\n")
    lfile.close()

walk(os.curdir)
