#!/usr/bin/python

import os

template = "template.html"
embed_mark = "<!--markdown-->"

# get template
tfile = open(template)
temp_str = tfile.read()
tfile.close()
begin = temp_str.find(embed_mark)
end = begin + len(embed_mark)
temp_head = temp_str[:begin]
temp_tail = temp_str[end:]

articles = []

def process_file(path, fname):
    input_name = "{}/{}".format(path, fname);
    output_name = input_name[:-3] + ".html" # remove .md ending
    articles.append(output_name) # record processed files
    f = open(output_name, "w")
    f.write(temp_head)
    f.close()
    os.system("md2html '{}' >> '{}'".format(input_name, output_name))
    f = open(output_name, "a")
    f.write(temp_tail)
    f.close()

def walk(path):
    for dpath, dnames, fnames in os.walk(path):
        for fn in fnames:
            if fn.endswith(".md"):
                process_file(dpath, fn)
        for dir in dnames:
            walk("{}/{}".format(dpath, dir))

walk(os.curdir)

# dump articles
import json
lfile = open("list.json", "w")
lfile.write(json.dumps(articles))
lfile.write("\n")
lfile.close()
