#!/usr/bin/fish

function build_file
	set ifile $argv[1]'.md'
	set ofile $argv[1]'.html'
	cat .mayfly/header.html > ofile
	cat $argv[1]'.md' | markdown2html >> ofile
	cat .mayfly/footer.html > ofile
end


function build_directory
	read --null --array pages < .mayfly/page.list
	for p in pages
		build_file p
	end
end


function init_directory
	mkdir .mayfly
	touch .mayfly/page.list
	touch .mayfly/header.html
	touch .mayfly/footer.html
end


function init_page -a page
	touch $page'.md'
	echo $page >> .mayfly/page.list
end


function add_page -a page
	echo $page >> .mayfly/page.list
end
